import { useCytoscape } from "../index";
import { useEffect } from "react";

export function useSchemaStyleLayer() {
  const nodeSchemas = {
    MST_Employee: {
      name: "MST_Employee",
      displayProperty: "MST_Employee.name",
      displayName: "员工",
      icon: "user",
      color: "rgba(30,186,30,1)",
      biConfig: "",
      cid: null,
      hasSchemaSet: true,
      properties: [
        {
          name: "employee_number",
          predicate: "MST_Employee.employee_number",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Employee",
          hide: false,
        },
        {
          name: "name",
          predicate: "MST_Employee.name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Employee",
          hide: false,
        },
        {
          name: "employeeid",
          predicate: "MST_Employee.employeeid",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Employee",
          hide: false,
        },
        {
          name: "full_name",
          predicate: "MST_Employee.full_name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Employee",
          hide: false,
        },
        {
          name: "oldnumber",
          predicate: "MST_Employee.oldnumber",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Employee",
          hide: false,
        },
      ],
      relationships: [
        {
          name: "employee_to_supplier_internal",
          predicate: "MST_Employee.employee_to_supplier_internal",
          displayName: "员工与供应商内部关系",
          sourceNode: "MST_Employee",
          targetNode: "MST_Supplier",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: true,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "role",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "relation_type",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "scenario",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.638057",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
      ],
      remark: null,
      createdBy: "admin",
      createdDate: "2025-04-14T17:22:24.63896",
      lastModifiedBy: null,
      lastModifiedDate: null,
    },
    MST_Event: {
      name: "MST_Event",
      displayProperty: "MST_Event.name",
      displayName: "事件",
      icon: "comment-alt",
      color: "rgba(189,189,21,1)",
      biConfig: "",
      cid: null,
      hasSchemaSet: true,
      properties: [
        {
          name: "event_key",
          predicate: "MST_Event.event_key",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "name",
          predicate: "MST_Event.name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "classification",
          predicate: "MST_Event.classification",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "event_object",
          predicate: "MST_Event.event_object",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "event_date",
          predicate: "MST_Event.event_date",
          type: "datetime",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["day"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "type_l1",
          predicate: "MST_Event.type_l1",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "type_l2",
          predicate: "MST_Event.type_l2",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "description",
          predicate: "MST_Event.description",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "is_key_event",
          predicate: "MST_Event.is_key_event",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "abnormal_behavior_or_result",
          predicate: "MST_Event.abnormal_behavior_or_result",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "url_name",
          predicate: "MST_Event.url_name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "url_address",
          predicate: "MST_Event.url_address",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "key1",
          predicate: "MST_Event.key1",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "value1",
          predicate: "MST_Event.value1",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "key2",
          predicate: "MST_Event.key2",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "value2",
          predicate: "MST_Event.value2",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "key3",
          predicate: "MST_Event.key3",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "value3",
          predicate: "MST_Event.value3",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "key4",
          predicate: "MST_Event.key4",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "value4",
          predicate: "MST_Event.value4",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "key5",
          predicate: "MST_Event.key5",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
        {
          name: "value5",
          predicate: "MST_Event.value5",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Event",
          hide: false,
        },
      ],
      relationships: [],
      remark: null,
      createdBy: "admin",
      createdDate: "2025-04-14T17:22:24.639482",
      lastModifiedBy: null,
      lastModifiedDate: null,
    },
    MST_Item: {
      name: "MST_Item",
      displayProperty: "MST_Item.name",
      displayName: "物料",
      icon: "box-full",
      color: "rgba(173,66,14,1)",
      biConfig: "",
      cid: null,
      hasSchemaSet: true,
      properties: [
        {
          name: "code",
          predicate: "MST_Item.code",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash", "trigram"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "name",
          predicate: "MST_Item.name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "version",
          predicate: "MST_Item.version",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "lastest_version",
          predicate: "MST_Item.lastest_version",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "createtime",
          predicate: "MST_Item.createtime",
          type: "datetime",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["day"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "creator",
          predicate: "MST_Item.creator",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "modifier",
          predicate: "MST_Item.modifier",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "restricted_state",
          predicate: "MST_Item.restricted_state",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "status",
          predicate: "MST_Item.status",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "source",
          predicate: "MST_Item.source",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "last_updated_time",
          predicate: "MST_Item.last_updated_time",
          type: "datetime",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["day"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "process_name",
          predicate: "MST_Item.process_name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "category_code",
          predicate: "MST_Item.category_code",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "state",
          predicate: "MST_Item.state",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "product_line",
          predicate: "MST_Item.product_line",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "product",
          predicate: "MST_Item.product",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "lifecycle_state",
          predicate: "MST_Item.lifecycle_state",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "template",
          predicate: "MST_Item.template",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
        {
          name: "modify_time",
          predicate: "MST_Item.modify_time",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Item",
          hide: false,
        },
      ],
      relationships: [
        {
          name: "split",
          predicate: "MST_Item.split",
          displayName: "物料与物料拆分关系",
          sourceNode: "MST_Item",
          targetNode: "MST_Item",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: true,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "change_description",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "change_type",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.63994",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
        {
          name: "temp_code",
          predicate: "MST_Item.temp_code",
          displayName: "物料与物料临时与正式编码关系",
          sourceNode: "MST_Item",
          targetNode: "MST_Item",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "change_description",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "change_type",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.639959",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
        {
          name: "substitution",
          predicate: "MST_Item.substitution",
          displayName: "物料与物料替代关系",
          sourceNode: "MST_Item",
          targetNode: "MST_Item",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "change_description",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "change_type",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.639974",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
        {
          name: "item_to_supplier",
          predicate: "MST_Item.item_to_supplier",
          displayName: "物料与供应商关系",
          sourceNode: "MST_Item",
          targetNode: "MST_Supplier",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "relation_type",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.639991",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
        {
          name: "item_to_employee",
          predicate: "MST_Item.item_to_employee",
          displayName: "物料与员工关系",
          sourceNode: "MST_Item",
          targetNode: "MST_Employee",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "relation_type",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.640006",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
        {
          name: "item_to_event",
          predicate: "MST_Item.item_to_event",
          displayName: "物料与事件",
          sourceNode: "MST_Item",
          targetNode: "MST_Event",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "key3",
              displayName: "",
            },
            {
              propertyType: "datetime",
              propertyKey: "start_date",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "key1",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "key2",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "value1",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "value2",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "relation_type_l2",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "relation_type_l1",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "value3",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.640022",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
      ],
      remark: null,
      createdBy: "admin",
      createdDate: "2025-04-14T17:22:24.640029",
      lastModifiedBy: null,
      lastModifiedDate: null,
    },
    MST_Project: {
      name: "MST_Project",
      displayProperty: "MST_Project.name",
      displayName: "项目",
      icon: "clipboard-list-check",
      color: "rgba(204,6,177,1)",
      biConfig: "",
      cid: null,
      hasSchemaSet: true,
      properties: [
        {
          name: "project_no",
          predicate: "MST_Project.project_no",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "name",
          predicate: "MST_Project.name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "background",
          predicate: "MST_Project.background",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "classification",
          predicate: "MST_Project.classification",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "start_date",
          predicate: "MST_Project.start_date",
          type: "datetime",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["day"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "end_date",
          predicate: "MST_Project.end_date",
          type: "datetime",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["day"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "status",
          predicate: "MST_Project.status",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "type_name",
          predicate: "MST_Project.type_name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "team",
          predicate: "MST_Project.team",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "kind",
          predicate: "MST_Project.kind",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "risk",
          predicate: "MST_Project.risk",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "classificationl1",
          predicate: "MST_Project.classificationl1",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "classificationl2",
          predicate: "MST_Project.classificationl2",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
        {
          name: "classificationl3",
          predicate: "MST_Project.classificationl3",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Project",
          hide: false,
        },
      ],
      relationships: [
        {
          name: "project_to_item",
          predicate: "MST_Project.project_to_item",
          displayName: "项目与物料关系",
          sourceNode: "MST_Project",
          targetNode: "MST_Item",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "relation_type",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "scenario",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "scenario_l1",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.640334",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
        {
          name: "project_to_event",
          predicate: "MST_Project.project_to_event",
          displayName: "项目与事件关系",
          sourceNode: "MST_Project",
          targetNode: "MST_Event",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "datetime",
              propertyKey: "start_date",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "key3",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "key1",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "key2",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "value1",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "value2",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "value3",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "event_name",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.640352",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
        {
          name: "project_to_employee",
          predicate: "MST_Project.project_to_employee",
          displayName: "项目与员工关系",
          sourceNode: "MST_Project",
          targetNode: "MST_Employee",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-20T10:43:48.773221",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
        {
          name: "project_to_supplier",
          predicate: "MST_Project.project_to_supplier",
          displayName: "项目与供应商关系",
          sourceNode: "MST_Project",
          targetNode: "MST_Supplier",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "scenario",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-20T10:43:48.773239",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
      ],
      remark: null,
      createdBy: "admin",
      createdDate: "2025-04-14T17:22:24.640362",
      lastModifiedBy: null,
      lastModifiedDate: null,
    },
    MST_Supplier: {
      name: "MST_Supplier",
      displayProperty: "MST_Supplier.name",
      displayName: "供应商",
      icon: "city",
      color: "rgba(36,166,166,1)",
      biConfig: "",
      cid: null,
      hasSchemaSet: true,
      properties: [
        {
          name: "code",
          predicate: "MST_Supplier.code",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Supplier",
          hide: false,
        },
        {
          name: "name",
          predicate: "MST_Supplier.name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Supplier",
          hide: false,
        },
        {
          name: "former_name",
          predicate: "MST_Supplier.former_name",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["term"],
          displayName: null,
          node: "MST_Supplier",
          hide: false,
        },
        {
          name: "type_class",
          predicate: "MST_Supplier.type_class",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Supplier",
          hide: false,
        },
        {
          name: "business_type",
          predicate: "MST_Supplier.business_type",
          type: "string",
          list: false,
          index: true,
          notNull: false,
          primaryKey: null,
          tokenizer: ["hash"],
          displayName: null,
          node: "MST_Supplier",
          hide: false,
        },
      ],
      relationships: [
        {
          name: "tyc_bwtween_supplier",
          predicate: "MST_Supplier.tyc_bwtween_supplier",
          displayName: "天眼查关系",
          sourceNode: "MST_Supplier",
          targetNode: "MST_Supplier",
          biConfig: null,
          color: "#cccccc",
          notNull: false,
          reverse: true,
          count: false,
          list: true,
          curve: "bezier",
          arrow: "triangle",
          width: 1,
          properties: [
            {
              propertyType: "string",
              propertyKey: "relations_link",
              displayName: "",
            },
            {
              propertyType: "string",
              propertyKey: "lev",
              displayName: "",
            },
          ],
          remark: null,
          createdBy: "admin",
          createdDate: "2025-04-14T17:22:24.640497",
          lastModifiedBy: null,
          lastModifiedDate: null,
        },
      ],
      remark: null,
      createdBy: "admin",
      createdDate: "2025-04-14T17:22:24.640506",
      lastModifiedBy: null,
      lastModifiedDate: null,
    },
  };

  const getSchemaStyleValue = (node, key, defaultValue?) => {
    const type = node.data("types")?.[0] || node.data("type");
    if (!type) return defaultValue;
    const schema = nodeSchemas?.[type];
    return schema?.[key] || defaultValue;
  };

  const cy = useCytoscape();
  useEffect(() => {
    cy.style().layer("schema", [
      {
        selector: "node:childless",
        style: {
          color: (ele) => getSchemaStyleValue(ele, "color", "#121312"),
          "background-color": (ele) =>
            getSchemaStyleValue(ele, "color", "#121312"),
          "background-image": (ele) =>
            `/fa-icons/${getSchemaStyleValue(ele, "icon", "object-group")}.png`,
        },
      },
    ]);
  }, [nodeSchemas]);
}
